site_name: MCPOmni Connect Documentation
site_description: Universal Gateway to MCP Servers - Intelligent AI Agent System
site_author: Abiola Adeshina
site_url: https://abiorh001.github.io/mcp_omni_connect

repo_name: Abiorh001/mcp_omni_connect
repo_url: https://github.com/Abiorh001/mcp_omni_connect
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Configuration:
    - Configuration Guide: configuration/configuration-guide.md
    - Transport Types: configuration/transport-types.md
    - Authentication: configuration/authentication.md
    - LLM Providers: configuration/llm-providers.md
    - Troubleshooting: configuration/troubleshooting.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Operation Modes: user-guide/operation-modes.md
    - Commands: user-guide/commands.md
    - Memory Management: user-guide/memory-management.md
    - Prompt Management: user-guide/prompt-management.md
  - Features:
    - Agent System: features/agent-system.md
    - Tool Orchestration: features/tool-orchestration.md
    - Resource Management: features/resource-management.md
    - Token Management: features/token-management.md
  - Advanced:
    - Architecture: advanced/architecture.md
    - API Reference: advanced/api-reference.md
    - Examples: advanced/examples.md
  - Development:
    - Testing: development/testing.md
    - Contributing: development/contributing.md
  - Changelog: changelog.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: abiorh001
      repo: mcp_omni_connect
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Abiorh001/mcp_omni_connect
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mcpomni-connect/
  version:
    provider: mike

copyright: Copyright &copy; 2024 Abiola Adeshina 